# 워크플로우의 이름
name: calculate-project

# github 리소스에 접근할 수 있는 권한 범위
permissions:
  contents: read
  pull-requests: write

on: # 이벤트
  push:
    # main 브랜치로 push되면 워크플로우 실행
    branches:
      - "main"

jobs:
  build:
    # github가 제공하는 최신 Ubuntu runner에서 실행
    runs-on: ubuntu-latest
    steps:
      # 레포지토리 소스 코드를 runner로 가져오는 작업
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install envsubst
        # 환경 변수 변환을 위해 설치 (템플릿안의 ${변수명}을 실제 환경 변수 값으로 바꿔주는 도구 포함)
        run: sudo apt-get install -y gettext

      - name: Create application.yml.template
        run: |
          mkdir -p src/main/resources
          cat > src/main/resources/application.yml.template <<EOL
          spring:
            application: 
              name: practice-github-actions
          
          server:
            port: 10000
          
          EOL

      - name: Build with Gradle
        run: ./gradlew clean build test
        shell: bash
